[package]
name = "minecrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
bytemuck = { version = "1.9.1", features = ["derive"] }
winit = "0.26.1"
wgpu = { git = "https://github.com/gfx-rs/wgpu" }
# glam = "0.20.5"
cgmath = "0.18"