[package]
name = "minecrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
pollster = "0.2"  # let's you block on futures (like await in Javascript)
winit = "0.26.1"
wgpu = "0.12.0"